### PR TITLE
Added HDR mode for primer design

### PR DESCRIPTION
**Pull request by gregdingle**
This adds the changes we need for primer design for HDR. The HDR code path is activated by passing in a GET param 'hdrDist', which denotes the distance from the current guide to the HDR insert point. The primer design is centered on the insert point. 

The changes may be useful to other consumers in the current form,  or they may require proper integration into the UI, in which case this can remain an experimental or undocumented feature. 

NOTE: my editor removed all the extraneous whitespace automatically, resulting in many lines of change. See designPrimer for significant changes.

TEST PLAN:

Try the HDR mode on the forked server: http://ec2-34-219-237-20.us-west-2.compute.amazonaws.com/crispor.py?ampLen=300&tm=60&batchId=eZJ4ZqDqOyb94bkSKMu5&pamId=s28%2B&pam=NGG&hdrDist=22#ontargetPcr . See primer product centered on the insert point within the larger size range. 

Try without the `hdrDist` and see the same result as before on http://crispor.tefor.net . http://ec2-34-219-237-20.us-west-2.compute.amazonaws.com/crispor.py?ampLen=300&tm=60&batchId=eZJ4ZqDqOyb94bkSKMu5&pamId=s28%2B&pam=NGG#ontargetPcr .

### CODE REVIEW

**Comment by maximilianh** [comment]
Sorry, I thought I had commented on this PR but apparently didn't!
Thanks, this is definitely a step in the right direction!

So this is only for an insertion? and the user specifies the insertion point on the target sequence ?

**Comment by gregdingle** [comment]
Yes this adds a code path for insertion. The user specifies the insertion
point relative to the guide cut point.

**Comment by maximilianh** [comment]
Yes, that's an interesting addition, but it will require much more UI...

**Comment by jpconcordet** [comment]
I just wished I was able to have a look and figure out whether this addition is useful or not !!

**Comment by gregdingle** [comment]
I agree it will take more UI for others to use.


The minimal amount would be an optional text input in the PCR primer
section., labeled something like “center primers around position X bp from
guide cut position for optimal HDR”. The input could take positive or
negative numbers.

**Comment by maximilianh** [comment]
Jean Paul thinks that users should make the insert position with a special
character in the input sequence. Since he’s on the thread, he may be able
to explain it better himself...

**Comment by jpconcordet** [comment]
When you are designing PCR primers with Primer 3, special characters can be used very easily to highlight specific positions in the input sequence .
So I’ve just been thinking the same approach could be used for CRISPOR !
Inserting a special character would make it very easy track the insert position without having to count distances.

Let’s say you want to make an insertion just before a STOP codon (a standard design of genome editing to insert peptide tags in protein coding sequences)/
You could use the ^ character as here below:
CCCCCCCCCCCCCCCCCCC^TAAcccccccccccccccc

**Comment by gregdingle** [comment]
@jpconcordet That makes sense. For the Crispor UI, would you submit the annotated sequence in the "Step 1" input? Then Crispor would need to process the annotated sequence and store the insert position so that it could be used when primers are requested. 

Another benefit of having this information would be to rank the guides by cut-to-insert distance, a must-do for guide design for HDR. Crispycrunch currently does this on its side.

**Comment by maximilianh** [comment]
I'm wondering more and more, especially for your application: Why not
repcalculate this for all human genes?

**Comment by gregdingle** [comment]
> I'm wondering more and more, especially for your application: Why not
repcalculate this for all human genes?

Yes, that's a good question. I'll ask my team. I think their answer will be that they still want to the flexbility of manually choosing from the Crispor UI their preferred guides. 

For what it's worth, I estimated that crispycrunch coud pre-calculate all possible guides and primers for HDR of interest in hg38 in 2 to 4 days at current performance.

**Comment by maximilianh** [comment]
If you use the pre-calculated guides from genome.ucsc.edu (I ran crispor on
all exons already), it may even be a lot quicker, on the order of minutes.
Your colleagues could still choose the guides, though it wouldn't be in the
crispor interface... hmm...

**Comment by gregdingle** [comment]
I asked my team about pre-calculating guides and they said they want the flexibility of doing it dynamically. If they didn't, they would be using a pre-existing library already. 

So what do you guys want to do with this PR? I would like to see it merged so we don't need to maintain a stale fork. We've already been bitten once by not keeping up with master. 

I don't see any harm in merging this PR as-is. It would simply add an undocumented HDR mode for primer design.

**Comment by maximilianh** [comment]
Sorry for the delay! This is fine. I just had handle the merge conflict.

**Comment by maximilianh** [comment]
Hm, interesting...pre-calculation may not mean giving them only one option.
We could give them 100+ different guides to pick from. Or all that make
some minimal sense...?

Yes, there shouldn't be any harm in adding this. Sorry for the delay.

**Pull request merged**
