### PR TITLE
tiny encode bug

### PR DESCRIPTION
**Pull request by flashlab**

### CODE REVIEW

**Comment by flashlab** [comment]
Hi, maximilianh
Though it might not be crucial bug, but I still hope it'll be fixed ;)

**Comment by maximilianh** [comment]
Thanks! this patch looks like a very good idea!

**Comment by maximilianh** [comment]
Oh and just curious: are you running a local copy of the crispor site?

**Comment by flashlab** [comment]
@maximilianh no, It was hosted on [our websites](http://fly.med.tsinghua.edu.cn/grna.php). I'm not sure if I should cite somewhere or ask for your permission, sorry about that.

**Comment by maximilianh** [comment]
Hi Jeff,

thanks for the patch, you're an academic lab, no need to cite or ask for
permission. But I do appreciate if you tell me that you're using it. Also,
if you publish papers where you used crispor, I appreciate a citation of
the crispor paper:
genomebiology.biomedcentral.com/articles/10.1186/s13059-016-1012-2

thanks again,
Max

**Comment by flashlab** [comment]
Hi, Max
Thanks for your kindness reply. Sure we'll cite your paper if cispor is being used. Again, thanks for sharing the amazing tools ;)
, Zheng

**Pull request merged**
